@authurl=https://4395c46atrial.authentication.us10.hana.ondemand.com
@clientId=sb-cap-openapi-4395c46atrial-dev!t230421
@clientSecret=K9xODcRAfztUdjadpMLExYOK8aU=
@appurl=4395c46atrial-dev-cap-openapi-srv.cfapps.us10-001.hana.ondemand.com

### Get JWT token
# @name getCredentials
POST {{authurl}}/oauth/token?grant_type=client_credentials
Authorization: Basic {{clientId}} {{clientSecret}}

@token =  {{getCredentials.response.body.access_token}}

###
GET {{appurl}}/odata/v4/AuthorizationService/getRoleCollections()
Authorization: Bearer {{token}}